/**
 * Tool icon lookup.
 *
 * Each tool declares its icon as a string (Lucide icon name) so the registry
 * can live in a plain data file. Here we map those strings to actual Lucide
 * components at module load time. Unknown names resolve to `FALLBACK_ICON`.
 *
 * Why a static map instead of dynamic `import()`: the Lucide icon set is
 * already tree-shakable and we want zero runtime surprises. Tools are expected
 * to pick from this allowlist; Phase 3 can append entries freely.
 */

import {
  Activity,
  AlignLeft,
  Archive,
  Binary,
  Braces,
  Brackets,
  Calculator,
  Calendar,
  CaseSensitive,
  Clock,
  Code2,
  CodeXml,
  Cog,
  Database,
  Diff,
  Download,
  Eraser,
  Eye,
  FileCode2,
  FileCog,
  FileDown,
  FileJson,
  FileSpreadsheet,
  FileText,
  Film,
  Filter,
  Fingerprint,
  Flag,
  Globe,
  Hash,
  Image as ImageIcon,
  Images,
  Key,
  KeyRound,
  Link,
  Link2,
  List,
  Lock,
  Magnet,
  Minimize2,
  Music,
  Package,
  Palette,
  Percent,
  Pilcrow,
  QrCode,
  Quote,
  Regex,
  Repeat,
  RotateCw,
  Ruler,
  Scale,
  Scan,
  Scissors,
  Search,
  Settings2,
  Shield,
  ShieldCheck,
  Shuffle,
  Sigma,
  Smartphone,
  Sparkles,
  Stamp,
  Terminal,
  Timer,
  ToggleLeft,
  Type,
  Unlock,
  Upload,
  Wand2,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const FALLBACK_ICON: LucideIcon = Wrench;

const ICON_REGISTRY: Record<string, LucideIcon> = {
  activity: Activity,
  'align-left': AlignLeft,
  archive: Archive,
  binary: Binary,
  braces: Braces,
  brackets: Brackets,
  calculator: Calculator,
  calendar: Calendar,
  'case-sensitive': CaseSensitive,
  clock: Clock,
  code: Code2,
  'code-2': Code2,
  'code-xml': CodeXml,
  cog: Cog,
  database: Database,
  diff: Diff,
  download: Download,
  eraser: Eraser,
  eye: Eye,
  'file-code': FileCode2,
  'file-cog': FileCog,
  'file-down': FileDown,
  'file-json': FileJson,
  'file-spreadsheet': FileSpreadsheet,
  'file-text': FileText,
  film: Film,
  filter: Filter,
  fingerprint: Fingerprint,
  flag: Flag,
  globe: Globe,
  hash: Hash,
  image: ImageIcon,
  images: Images,
  key: Key,
  'key-round': KeyRound,
  link: Link,
  'link-2': Link2,
  list: List,
  lock: Lock,
  magnet: Magnet,
  'minimize-2': Minimize2,
  music: Music,
  package: Package,
  palette: Palette,
  percent: Percent,
  pilcrow: Pilcrow,
  'qr-code': QrCode,
  quote: Quote,
  regex: Regex,
  repeat: Repeat,
  'rotate-cw': RotateCw,
  ruler: Ruler,
  scale: Scale,
  scan: Scan,
  scissors: Scissors,
  search: Search,
  settings: Settings2,
  shield: Shield,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  sigma: Sigma,
  smartphone: Smartphone,
  sparkles: Sparkles,
  stamp: Stamp,
  terminal: Terminal,
  timer: Timer,
  'toggle-left': ToggleLeft,
  type: Type,
  unlock: Unlock,
  upload: Upload,
  wand: Wand2,
  wrench: Wrench,
};

/**
 * Resolve a tool icon name to its Lucide component. Safe to call with
 * unknown names — returns `FALLBACK_ICON` rather than throwing.
 */
export const getToolIcon = (name: string | undefined | null): LucideIcon => {
  if (!name) return FALLBACK_ICON;
  const key = name.toLowerCase().trim();
  return ICON_REGISTRY[key] ?? FALLBACK_ICON;
};
